name: encodingmodel_py39
channels:
  - conda-forge
dependencies:
  - python=3.9
  - tqdm
  - matplotlib
  - seaborn
  - pandas
  - scikit-learn
  - numpy
  - hdf5storage
  - dill
  - textgrid
  - tiktoken==0.3.3
  - more-itertools
  - numba
  - cupy
  - pytest
  - pytest-rerunfailures
  - scipy
  - openai
  - dask
  - pysoundfile
  - gensim
  - omegaconf
  - flask
  - hydra-core
  - jupyterlab
  - librosa
  - optuna
  - python-levenshtein
  - pytorch-lightning>=1.7.0
  - sox
  - psutil
  - mpld3
  - cox
  - einops
  - montreal-forced-aligner
  - cvxopt

  - pip
  - pip:
    - torch
    - torchvision
    - torchaudio
    - torchelastic
    - jupyter-matlab-proxy
    - mlens
    - hydra-core
    - dfply
    - transformers
    - datasets
    - /scratch/snormanh_lab/shared/code/my_himalaya
    - /scratch/snormanh_lab/shared/code/my_whisper
    - /scratch/snormanh_lab/shared/code/snormanh_lab_python
    - git+https://github.com/romesco/hydra-lightning/#subdirectory=hydra-configs-pytorch-lightning
    - git+https://github.com/SeanNaren/deepspeech.pytorch.git

